version: "3.8"

networks:
  board-network:

services:
  board_mongodb:
    image: mongo:4.4.10
    container_name: board_mongodb
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: board
      MONGO_INITDB_ROOT_PASSWORD: board
      MONGO_INITDB_DATABASE: board
      TZ: "Asia/Seoul"
    volumes:
      - ./volumes/mongodb/data:/data/db
      - ./volumes/mongodb/log:/var/log/mongodb/
    ports:
      - 27017:27017
    command: mongod
    networks:
      - board-network

  board:
    image: board:0.02
    container_name: board
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - ./../frontend/build:/usr/src/client
    ports:
      - 80:3000
    command: yarn start:dev
    depends_on:
      - board_mongodb
    networks:
      - board-network
